apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-app
  namespace: polling-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polling-app
  template:
    metadata:
      labels:
        app: polling-app
    spec:
      containers:
      - name: polling-app
        image: dhavalbhimani44/polling-app:dev
        ports:
        - containerPort: 5000