apiVersion: v1
kind: Service
metadata:
  name: polling-service
  namespace: polling-dev
spec:
  type: NodePort
  selector:
    app: polling-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
